---
name: taskly
services:
  ui:
    build:
      context: ./frontend
    command: ["npm", "run", "dev"]
    environment:
      TASKLY_API_URL: "http://api:3030"
    volumes:
      - type: bind
        source: ./frontend/src
        target: /taskly-ui/src
    ports:
      - "3000:3000"
  api:
    build:
      context: ./backend
    command: ["npm", "run", "dev"]
    volumes:
      - type: bind
        source: ./backend/src
        target: /taskly-api/src
    ports:
      - "3030:3030"
